### ISSUE TITLE
Was there any efforts made to port this extension?

### ISSUE THREAD

**Issue by nikitavoloboev** [flippidippi/sVim#123]
I am currently in the process of reading Safari extension docs trying to understand what's needed in order to port this to work on Safari 12.

I am curious if there has been any efforts that were made in this direction? Ideally open source.

**Comment by de-Blaxe** [comment]
I'd be interested in helping out. I'm in the process of porting over a similar extension called Vimium.

**Comment by de-Blaxe** [comment]
@nikitavoloboev How familiar are you with Swift? I need some help figuring out how to port over the persistent & editable behavior of sVimrc.html

**Comment by nikitavoloboev** [comment]
Never wrote much of it. If you share code and what you are trying to do, I can look into it.

**Comment by flippidippi** [comment]
Duplicate of https://github.com/flippidippi/sVim/issues/94
