### ISSUE TITLE
Blacklist localhost

### ISSUE THREAD

**Issue by ky0on** [flippidippi/sVim#78]
Can't I disable sVim at `http://localhost*`?

**Comment by wrtsprt** [comment]
I am having problems with ports. 
* "*://rmb15.local:9999/*"
* "*://rrr:9999/*"

don't work.

**Comment by ky0on** [comment]
I added `127.0.0.1   localhost.com` to `/etc/hosts`.
Then added `"*://localhost.com*/*"` to `blacklists` in `sVimrc`.

These disabled sVim on `http://localhost.com:8888` (=`http://localhost:8888`).

**Comment by bhishanpdl** [comment]
svim plugin blacklist does not work in "http://localhost:8888/*".

```
let blacklists = [ "*://localhost.com*/*", "*://localhost:*", "*://codepen.io/*", "*://draw.io/*", "*://*slack.com/*", "*://codesandbox.io/*", "*://codewars.com/*", "*://discordapp.com/*", "://gitter.im/*"]
```

**Comment by janek** [comment]
Has anyone found a simple workaround for this or could shed some light on why it doesn't work?
 
For a moment I thought I was able to use `127.0.0.1` explicitly and block it, but doesn't seem to be the case anymore.
